# Generated by Django 2.2.1 on 2019-05-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OSI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soc',
            old_name='stripend',
            new_name='stipend',
        ),
    ]
