# Generated by Django 2.2.1 on 2019-05-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSI', '0002_auto_20190510_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osc',
            old_name='osc_homepage',
            new_name='homepage',
        ),
        migrations.RenameField(
            model_name='soc',
            old_name='soc_homepage',
            new_name='homepage',
        ),
        migrations.AlterField(
            model_name='osc',
            name='timeline',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soc',
            name='timeline',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='univ_soc_woc',
            name='timeline',
            field=models.URLField(blank=True, null=True),
        ),
    ]
