# Generated by Django 2.2.1 on 2019-05-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_soc_soc_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soc',
            name='soc_homepage',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='soc',
            name='timeline',
            field=models.URLField(default=None),
        ),
    ]
