# Generated by Django 2.2.1 on 2019-05-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20190509_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soc',
            name='timeline',
            field=models.URLField(blank=True),
        ),
    ]
