# Generated by Django 2.2.1 on 2019-05-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20190509_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soc',
            name='timeline',
            field=models.URLField(blank=True, default=None),
        ),
    ]
