# Generated by Django 2.2.1 on 2019-05-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_univ_soc_woc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='univ_soc_woc',
            old_name='osc_homepage',
            new_name='homepage',
        ),
    ]
