# Generated by Django 2.2.1 on 2019-05-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20190510_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='osc',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soc',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='univ_soc_woc',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
