# Generated by Django 2.2.1 on 2019-05-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20190510_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osc',
            old_name='published',
            new_name='publish',
        ),
        migrations.RenameField(
            model_name='soc',
            old_name='published',
            new_name='publish',
        ),
        migrations.RenameField(
            model_name='univ_soc_woc',
            old_name='published',
            new_name='publish',
        ),
    ]
